config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :new, :show, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Submit my bookmark", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>My bookmark</h1>
<%= render "bookmarks/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80)">
  <div class="container">
    <h1><strong>Watch List </h1>
    <p>Save any kind of movie !</p>
    <p>
      <span id="banner-typed-text"></span>
      <%= link_to 'Create a new list', new_list_path(@list), class: "btn btn-ghost" %>
    </p>
  </div>
</div>


<div class="container-list">
  <div class="list-text">
    <h3>My Lists</h3>
    <%= link_to 'Create a new list', new_list_path(@list), class: "btn btn-success" %>
  </div>

  <div class="lists">
    <% @lists.each do |list| %>
      <%= link_to list.name, list_path(list) %>
    <% end %>
  </div>


</div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1578674473215-9e07ee2e577d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ4fHxtb3ZpZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  <div class="container">
  </div>
</div>

<div class="new-lists">
  <div class="new-list">
    <h1>Create my own movie <strong>list</strong> !</h1>
      <%= simple_form_for(@list) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner-list" style="background-image: url(https://images.unsplash.com/photo-1578674473215-9e07ee2e577d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ4fHxtb3ZpZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
<%# <p>= link_to 'My lists', lists_path(@list)</p> %>
<h1> <%= @list.name %></h1>
<p><%= link_to 'Add a movie to list', new_list_bookmark_path(@list), class: "btn btn-secondary" %></p>
</div>



<div class="movie-card">
<% @list.bookmarks.each do |bookmark| %>
        <div class="list-group-item">
          <%= image_tag bookmark.movie.poster_url, class:"poster-img" %>
            <div class="movie-card-text border border-2 me-3">
            <h4><strong><%= bookmark.movie.title %> • <%= bookmark.movie.rating %><i class="fas fa-star star-yellow"></i></strong></h4>
            <p><%= bookmark.movie.overview %></p>
            <h4><em>"<%= bookmark.comment %>"</em> - <%= link_to "🚮", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></h4>
          </div>
        </div>
<%end%>
  </div>

app/views/movies/overview:sting.html.erb
<h1>Movies#overview:sting</h1>
<p>Find me in app/views/movies/overview:sting.html.erb</p>

app/views/movies/poster_url:string.html.erb
<h1>Movies#poster_url:string</h1>
<p>Find me in app/views/movies/poster_url:string.html.erb</p>

app/views/movies/rating:integer.html.erb
<h1>Movies#rating:integer</h1>
<p>Find me in app/views/movies/rating:integer.html.erb</p>

app/views/movies/title:string.html.erb
<h1>Movies#title:string</h1>
<p>Find me in app/views/movies/title:string.html.erb</p>